from pdfform import PdfForm


class ICS213Form(PdfForm):
    """General Message Form (ICS 213)"""
    FIELD_MAPPING = {
        "1 Incident Name Optional": "incident_name",
        "2 To Name and Position": "to_name",
        "3 From Name and Position": "from_name",
        "4 Subject": "subject",
        "5 Date": "date",
        "6 Time": "time",
        "7 Message": "message_text",
        "8 Approved by Name": "approved_by_name",
        "Signature_19": "",
        "PositionTitle_13": "approved_by_position",
        "9 Reply": "reply_text",
        "10 Replied by Name": "replied_by_name",
        "PositionTitle_14": "replied_by_position",
        "Signature_20": "",
        "DateTime_14": "date_time"
    }

    incident_name = ''
    to_name = ''
    from_name = ''
    subject = ''
    date = ''
    time = ''
    message_text = ''
    approved_by_name = ''
    approved_by_position = ''
    reply_text = ''
    replied_by_name = ''
    replied_by_position = ''
    date_time = ''

    def __init__(self, pdf_file_path):
        super().__init__(pdf_file_path)

# TODO: Keep mapping the fields below
class ICS214Form(PdfForm):
    """Activity Log (ICS 214)"""
    FIELD_MAPPING = {
        "1 Incident Name_19": "incident_name",
        "3 Name": "recorder_name",
        "4 ICS Position": "recorder_position",
        "5 Home Agency and Unit": "recorder_agency",
        "NameRow1_3": "assigned_resource1",
        "ICS PositionRow1": "assigned_resource1_position",
        "Home Agency and UnitRow1": "assigned_resource1_agency",
        "NameRow2_3": "assigned_resource2",
        "ICS PositionRow2": "assigned_resource2_position",
        "Home Agency and UnitRow2": "assigned_resource2_agency",
        "NameRow3_3": "assigned_resource3",
        "ICS PositionRow3": "assigned_resource3_position",
        "Home Agency and UnitRow3": "assigned_resource3_agency",
        "NameRow4_3": "assigned_resource4",
        "ICS PositionRow4": "assigned_resource4_position",
        "Home Agency and UnitRow4": "assigned_resource4_agency",
        "NameRow5_3": "assigned_resource5",
        "ICS PositionRow5": "assigned_resource5_position",
        "Home Agency and UnitRow5": "assigned_resource5_agency",
        "NameRow6_3": "assigned_resource6",
        "ICS PositionRow6": "assigned_resource6_position",
        "Home Agency and UnitRow6": "assigned_resource6_agency",
        "NameRow7": "assigned_resource7",
        "ICS PositionRow7": "assigned_resource7_position",
        "Home Agency and UnitRow7": "assigned_resource7_agency",
        "NameRow8": "assigned_resource8",
        "ICS PositionRow8": "assigned_resource8_position",
        "Home Agency and UnitRow8": "assigned_resource8_agency",
        "DateTimeRow1": "notable_activity1_datetime",
        "Notable ActivitiesRow1": "notable_activity1",
        "DateTimeRow2": "notable_activity2_datetime",
        "Notable ActivitiesRow2": "notable_activity2",
        "DateTimeRow3": "notable_activity3_datetime",
        "Notable ActivitiesRow3": "notable_activity3",
        "DateTimeRow4": "notable_activity4_datetime",
        "Notable ActivitiesRow4": "notable_activity4",
        "DateTimeRow5": "notable_activity5_datetime",
        "Notable ActivitiesRow5": "notable_activity5",
        "DateTimeRow6": "notable_activity6_datetime",
        "Notable ActivitiesRow6": "notable_activity6",
        "DateTimeRow7": "notable_activity7_datetime",
        "Notable ActivitiesRow7": "notable_activity7",
        "DateTimeRow8": "notable_activity8_datetime",
        "Notable ActivitiesRow8": "notable_activity8",
        "DateTimeRow9": "notable_activity9_datetime",
        "Notable ActivitiesRow9": "notable_activity9",
        "DateTimeRow10": "notable_activity10_datetime",
        "Notable ActivitiesRow10": "notable_activity10",
        "DateTimeRow11": "notable_activity11_datetime",
        "Notable ActivitiesRow11": "notable_activity11",
        "DateTimeRow12": "",
        "Notable ActivitiesRow12": "",
        "DateTimeRow13": "",
        "Notable ActivitiesRow13": "",
        "DateTimeRow14": "",
        "Notable ActivitiesRow14": "",
        "DateTimeRow15": "",
        "Notable ActivitiesRow15": "",
        "DateTimeRow16": "",
        "Notable ActivitiesRow16": "",
        "DateTimeRow17": "",
        "Notable ActivitiesRow17": "",
        "DateTimeRow18": "",
        "Notable ActivitiesRow18": "",
        "DateTimeRow19": "",
        "Notable ActivitiesRow19": "",
        "DateTimeRow20": "",
        "Notable ActivitiesRow20": "",
        "DateTimeRow21": "",
        "Notable ActivitiesRow21": "",
        "DateTimeRow22": "",
        "Notable ActivitiesRow22": "",
        "DateTimeRow23": "",
        "Notable ActivitiesRow23": "",
        "DateTimeRow24": "",
        "Notable ActivitiesRow24": "",
        "8 Prepared by Name": "",
        "PositionTitle_15": "",
        "Signature_21": "",
        "DateTime_15": "",
        "1 Incident Name_20": "",
        "DateTimeRow1_2": "",
        "Notable ActivitiesRow1_2": "",
        "DateTimeRow2_2": "",
        "Notable ActivitiesRow2_2": "",
        "DateTimeRow3_2": "",
        "Notable ActivitiesRow3_2": "",
        "DateTimeRow4_2": "",
        "Notable ActivitiesRow4_2": "",
        "DateTimeRow5_2": "",
        "Notable ActivitiesRow5_2": "",
        "DateTimeRow6_2": "",
        "Notable ActivitiesRow6_2": "",
        "DateTimeRow7_2": "",
        "Notable ActivitiesRow7_2": "",
        "DateTimeRow8_2": "",
        "Notable ActivitiesRow8_2": "",
        "DateTimeRow9_2": "",
        "Notable ActivitiesRow9_2": "",
        "DateTimeRow10_2": "",
        "Notable ActivitiesRow10_2": "",
        "DateTimeRow11_2": "",
        "Notable ActivitiesRow11_2": "",
        "DateTimeRow12_2": "",
        "Notable ActivitiesRow12_2": "",
        "DateTimeRow13_2": "",
        "Notable ActivitiesRow13_2": "",
        "DateTimeRow14_2": "",
        "Notable ActivitiesRow14_2": "",
        "DateTimeRow15_2": "",
        "Notable ActivitiesRow15_2": "",
        "DateTimeRow16_2": "",
        "Notable ActivitiesRow16_2": "",
        "DateTimeRow17_2": "",
        "Notable ActivitiesRow17_2": "",
        "DateTimeRow18_2": "",
        "Notable ActivitiesRow18_2": "",
        "DateTimeRow19_2": "",
        "Notable ActivitiesRow19_2": "",
        "DateTimeRow20_2": "",
        "Notable ActivitiesRow20_2": "",
        "DateTimeRow21_2": "",
        "Notable ActivitiesRow21_2": "",
        "DateTimeRow22_2": "",
        "Notable ActivitiesRow22_2": "",
        "DateTimeRow23_2": "",
        "Notable ActivitiesRow23_2": "",
        "DateTimeRow24_2": "",
        "Notable ActivitiesRow24_2": "",
        "DateTimeRow25": "",
        "Notable ActivitiesRow25": "",
        "DateTimeRow26": "",
        "Notable ActivitiesRow26": "",
        "DateTimeRow27": "",
        "Notable ActivitiesRow27": "",
        "DateTimeRow28": "",
        "Notable ActivitiesRow28": "",
        "DateTimeRow29": "",
        "Notable ActivitiesRow29": "",
        "DateTimeRow30": "",
        "Notable ActivitiesRow30": "",
        "DateTimeRow31": "",
        "Notable ActivitiesRow31": "",
        "DateTimeRow32": "",
        "Notable ActivitiesRow32": "",
        "DateTimeRow33": "",
        "Notable ActivitiesRow33": "",
        "DateTimeRow34": "",
        "Notable ActivitiesRow34": "",
        "DateTimeRow35": "",
        "Notable ActivitiesRow35": "",
        "DateTimeRow36": "",
        "Notable ActivitiesRow36": "",
        "8 Prepared by Name_2": "",
        "PositionTitle_16": "",
        "Signature_22": "",
        "DateTime_16": ""

        # TODO: Add logic to track notable activity rows
        # TODO: Add code to update the resources assigned
    }
